// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: tailbus/v1/transport.proto

package transportpb

import (
	messagepb "github.com/alexanderfrey/tailbus/api/messagepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelayTargetKey []byte                 `protobuf:"bytes,1,opt,name=relay_target_key,json=relayTargetKey,proto3" json:"relay_target_key,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*TransportMessage_Envelope
	//	*TransportMessage_RoomEvent
	//	*TransportMessage_RoomCommand
	//	*TransportMessage_RoomCommandResult
	Body          isTransportMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportMessage) Reset() {
	*x = TransportMessage{}
	mi := &file_tailbus_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportMessage) ProtoMessage() {}

func (x *TransportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportMessage.ProtoReflect.Descriptor instead.
func (*TransportMessage) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *TransportMessage) GetRelayTargetKey() []byte {
	if x != nil {
		return x.RelayTargetKey
	}
	return nil
}

func (x *TransportMessage) GetBody() isTransportMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TransportMessage) GetEnvelope() *messagepb.Envelope {
	if x != nil {
		if x, ok := x.Body.(*TransportMessage_Envelope); ok {
			return x.Envelope
		}
	}
	return nil
}

func (x *TransportMessage) GetRoomEvent() *messagepb.RoomEvent {
	if x != nil {
		if x, ok := x.Body.(*TransportMessage_RoomEvent); ok {
			return x.RoomEvent
		}
	}
	return nil
}

func (x *TransportMessage) GetRoomCommand() *messagepb.RoomCommand {
	if x != nil {
		if x, ok := x.Body.(*TransportMessage_RoomCommand); ok {
			return x.RoomCommand
		}
	}
	return nil
}

func (x *TransportMessage) GetRoomCommandResult() *messagepb.RoomCommandResult {
	if x != nil {
		if x, ok := x.Body.(*TransportMessage_RoomCommandResult); ok {
			return x.RoomCommandResult
		}
	}
	return nil
}

type isTransportMessage_Body interface {
	isTransportMessage_Body()
}

type TransportMessage_Envelope struct {
	Envelope *messagepb.Envelope `protobuf:"bytes,2,opt,name=envelope,proto3,oneof"`
}

type TransportMessage_RoomEvent struct {
	RoomEvent *messagepb.RoomEvent `protobuf:"bytes,3,opt,name=room_event,json=roomEvent,proto3,oneof"`
}

type TransportMessage_RoomCommand struct {
	RoomCommand *messagepb.RoomCommand `protobuf:"bytes,4,opt,name=room_command,json=roomCommand,proto3,oneof"`
}

type TransportMessage_RoomCommandResult struct {
	RoomCommandResult *messagepb.RoomCommandResult `protobuf:"bytes,5,opt,name=room_command_result,json=roomCommandResult,proto3,oneof"`
}

func (*TransportMessage_Envelope) isTransportMessage_Body() {}

func (*TransportMessage_RoomEvent) isTransportMessage_Body() {}

func (*TransportMessage_RoomCommand) isTransportMessage_Body() {}

func (*TransportMessage_RoomCommandResult) isTransportMessage_Body() {}

var File_tailbus_v1_transport_proto protoreflect.FileDescriptor

const file_tailbus_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x1atailbus/v1/transport.proto\x12\n" +
	"tailbus.v1\x1a\x19tailbus/v1/messages.proto\"\xbf\x02\n" +
	"\x10TransportMessage\x12(\n" +
	"\x10relay_target_key\x18\x01 \x01(\fR\x0erelayTargetKey\x122\n" +
	"\benvelope\x18\x02 \x01(\v2\x14.tailbus.v1.EnvelopeH\x00R\benvelope\x126\n" +
	"\n" +
	"room_event\x18\x03 \x01(\v2\x15.tailbus.v1.RoomEventH\x00R\troomEvent\x12<\n" +
	"\froom_command\x18\x04 \x01(\v2\x17.tailbus.v1.RoomCommandH\x00R\vroomCommand\x12O\n" +
	"\x13room_command_result\x18\x05 \x01(\v2\x1d.tailbus.v1.RoomCommandResultH\x00R\x11roomCommandResultB\x06\n" +
	"\x04body2[\n" +
	"\rNodeTransport\x12J\n" +
	"\bExchange\x12\x1c.tailbus.v1.TransportMessage\x1a\x1c.tailbus.v1.TransportMessage(\x010\x01B2Z0github.com/alexanderfrey/tailbus/api/transportpbb\x06proto3"

var (
	file_tailbus_v1_transport_proto_rawDescOnce sync.Once
	file_tailbus_v1_transport_proto_rawDescData []byte
)

func file_tailbus_v1_transport_proto_rawDescGZIP() []byte {
	file_tailbus_v1_transport_proto_rawDescOnce.Do(func() {
		file_tailbus_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tailbus_v1_transport_proto_rawDesc), len(file_tailbus_v1_transport_proto_rawDesc)))
	})
	return file_tailbus_v1_transport_proto_rawDescData
}

var file_tailbus_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tailbus_v1_transport_proto_goTypes = []any{
	(*TransportMessage)(nil),            // 0: tailbus.v1.TransportMessage
	(*messagepb.Envelope)(nil),          // 1: tailbus.v1.Envelope
	(*messagepb.RoomEvent)(nil),         // 2: tailbus.v1.RoomEvent
	(*messagepb.RoomCommand)(nil),       // 3: tailbus.v1.RoomCommand
	(*messagepb.RoomCommandResult)(nil), // 4: tailbus.v1.RoomCommandResult
}
var file_tailbus_v1_transport_proto_depIdxs = []int32{
	1, // 0: tailbus.v1.TransportMessage.envelope:type_name -> tailbus.v1.Envelope
	2, // 1: tailbus.v1.TransportMessage.room_event:type_name -> tailbus.v1.RoomEvent
	3, // 2: tailbus.v1.TransportMessage.room_command:type_name -> tailbus.v1.RoomCommand
	4, // 3: tailbus.v1.TransportMessage.room_command_result:type_name -> tailbus.v1.RoomCommandResult
	0, // 4: tailbus.v1.NodeTransport.Exchange:input_type -> tailbus.v1.TransportMessage
	0, // 5: tailbus.v1.NodeTransport.Exchange:output_type -> tailbus.v1.TransportMessage
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tailbus_v1_transport_proto_init() }
func file_tailbus_v1_transport_proto_init() {
	if File_tailbus_v1_transport_proto != nil {
		return
	}
	file_tailbus_v1_transport_proto_msgTypes[0].OneofWrappers = []any{
		(*TransportMessage_Envelope)(nil),
		(*TransportMessage_RoomEvent)(nil),
		(*TransportMessage_RoomCommand)(nil),
		(*TransportMessage_RoomCommandResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tailbus_v1_transport_proto_rawDesc), len(file_tailbus_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tailbus_v1_transport_proto_goTypes,
		DependencyIndexes: file_tailbus_v1_transport_proto_depIdxs,
		MessageInfos:      file_tailbus_v1_transport_proto_msgTypes,
	}.Build()
	File_tailbus_v1_transport_proto = out.File
	file_tailbus_v1_transport_proto_goTypes = nil
	file_tailbus_v1_transport_proto_depIdxs = nil
}
