// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: tailbus/v1/messages.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvelopeType int32

const (
	EnvelopeType_ENVELOPE_TYPE_UNSPECIFIED     EnvelopeType = 0
	EnvelopeType_ENVELOPE_TYPE_MESSAGE         EnvelopeType = 1
	EnvelopeType_ENVELOPE_TYPE_SESSION_OPEN    EnvelopeType = 2
	EnvelopeType_ENVELOPE_TYPE_SESSION_RESOLVE EnvelopeType = 3
	EnvelopeType_ENVELOPE_TYPE_ACK             EnvelopeType = 4
)

// Enum value maps for EnvelopeType.
var (
	EnvelopeType_name = map[int32]string{
		0: "ENVELOPE_TYPE_UNSPECIFIED",
		1: "ENVELOPE_TYPE_MESSAGE",
		2: "ENVELOPE_TYPE_SESSION_OPEN",
		3: "ENVELOPE_TYPE_SESSION_RESOLVE",
		4: "ENVELOPE_TYPE_ACK",
	}
	EnvelopeType_value = map[string]int32{
		"ENVELOPE_TYPE_UNSPECIFIED":     0,
		"ENVELOPE_TYPE_MESSAGE":         1,
		"ENVELOPE_TYPE_SESSION_OPEN":    2,
		"ENVELOPE_TYPE_SESSION_RESOLVE": 3,
		"ENVELOPE_TYPE_ACK":             4,
	}
)

func (x EnvelopeType) Enum() *EnvelopeType {
	p := new(EnvelopeType)
	*p = x
	return p
}

func (x EnvelopeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvelopeType) Descriptor() protoreflect.EnumDescriptor {
	return file_tailbus_v1_messages_proto_enumTypes[0].Descriptor()
}

func (EnvelopeType) Type() protoreflect.EnumType {
	return &file_tailbus_v1_messages_proto_enumTypes[0]
}

func (x EnvelopeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvelopeType.Descriptor instead.
func (EnvelopeType) EnumDescriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{0}
}

type RoomEventType int32

const (
	RoomEventType_ROOM_EVENT_TYPE_UNSPECIFIED    RoomEventType = 0
	RoomEventType_ROOM_EVENT_TYPE_MEMBER_JOINED  RoomEventType = 1
	RoomEventType_ROOM_EVENT_TYPE_MEMBER_LEFT    RoomEventType = 2
	RoomEventType_ROOM_EVENT_TYPE_MESSAGE_POSTED RoomEventType = 3
	RoomEventType_ROOM_EVENT_TYPE_ROOM_CLOSED    RoomEventType = 4
)

// Enum value maps for RoomEventType.
var (
	RoomEventType_name = map[int32]string{
		0: "ROOM_EVENT_TYPE_UNSPECIFIED",
		1: "ROOM_EVENT_TYPE_MEMBER_JOINED",
		2: "ROOM_EVENT_TYPE_MEMBER_LEFT",
		3: "ROOM_EVENT_TYPE_MESSAGE_POSTED",
		4: "ROOM_EVENT_TYPE_ROOM_CLOSED",
	}
	RoomEventType_value = map[string]int32{
		"ROOM_EVENT_TYPE_UNSPECIFIED":    0,
		"ROOM_EVENT_TYPE_MEMBER_JOINED":  1,
		"ROOM_EVENT_TYPE_MEMBER_LEFT":    2,
		"ROOM_EVENT_TYPE_MESSAGE_POSTED": 3,
		"ROOM_EVENT_TYPE_ROOM_CLOSED":    4,
	}
)

func (x RoomEventType) Enum() *RoomEventType {
	p := new(RoomEventType)
	*p = x
	return p
}

func (x RoomEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_tailbus_v1_messages_proto_enumTypes[1].Descriptor()
}

func (RoomEventType) Type() protoreflect.EnumType {
	return &file_tailbus_v1_messages_proto_enumTypes[1]
}

func (x RoomEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomEventType.Descriptor instead.
func (RoomEventType) EnumDescriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{1}
}

type RoomCommandType int32

const (
	RoomCommandType_ROOM_COMMAND_TYPE_UNSPECIFIED  RoomCommandType = 0
	RoomCommandType_ROOM_COMMAND_TYPE_CREATE       RoomCommandType = 1
	RoomCommandType_ROOM_COMMAND_TYPE_JOIN         RoomCommandType = 2
	RoomCommandType_ROOM_COMMAND_TYPE_LEAVE        RoomCommandType = 3
	RoomCommandType_ROOM_COMMAND_TYPE_POST         RoomCommandType = 4
	RoomCommandType_ROOM_COMMAND_TYPE_REPLAY       RoomCommandType = 5
	RoomCommandType_ROOM_COMMAND_TYPE_LIST_MEMBERS RoomCommandType = 6
	RoomCommandType_ROOM_COMMAND_TYPE_CLOSE        RoomCommandType = 7
)

// Enum value maps for RoomCommandType.
var (
	RoomCommandType_name = map[int32]string{
		0: "ROOM_COMMAND_TYPE_UNSPECIFIED",
		1: "ROOM_COMMAND_TYPE_CREATE",
		2: "ROOM_COMMAND_TYPE_JOIN",
		3: "ROOM_COMMAND_TYPE_LEAVE",
		4: "ROOM_COMMAND_TYPE_POST",
		5: "ROOM_COMMAND_TYPE_REPLAY",
		6: "ROOM_COMMAND_TYPE_LIST_MEMBERS",
		7: "ROOM_COMMAND_TYPE_CLOSE",
	}
	RoomCommandType_value = map[string]int32{
		"ROOM_COMMAND_TYPE_UNSPECIFIED":  0,
		"ROOM_COMMAND_TYPE_CREATE":       1,
		"ROOM_COMMAND_TYPE_JOIN":         2,
		"ROOM_COMMAND_TYPE_LEAVE":        3,
		"ROOM_COMMAND_TYPE_POST":         4,
		"ROOM_COMMAND_TYPE_REPLAY":       5,
		"ROOM_COMMAND_TYPE_LIST_MEMBERS": 6,
		"ROOM_COMMAND_TYPE_CLOSE":        7,
	}
)

func (x RoomCommandType) Enum() *RoomCommandType {
	p := new(RoomCommandType)
	*p = x
	return p
}

func (x RoomCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_tailbus_v1_messages_proto_enumTypes[2].Descriptor()
}

func (RoomCommandType) Type() protoreflect.EnumType {
	return &file_tailbus_v1_messages_proto_enumTypes[2]
}

func (x RoomCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomCommandType.Descriptor instead.
func (RoomCommandType) EnumDescriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{2}
}

type Envelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromHandle     string                 `protobuf:"bytes,3,opt,name=from_handle,json=fromHandle,proto3" json:"from_handle,omitempty"`
	ToHandle       string                 `protobuf:"bytes,4,opt,name=to_handle,json=toHandle,proto3" json:"to_handle,omitempty"`
	Payload        []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType    string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SentAtUnix     int64                  `protobuf:"varint,7,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	Type           EnvelopeType           `protobuf:"varint,8,opt,name=type,proto3,enum=tailbus.v1.EnvelopeType" json:"type,omitempty"`
	TraceId        string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	AckId          string                 `protobuf:"bytes,11,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	RelayTargetKey []byte                 `protobuf:"bytes,12,opt,name=relay_target_key,json=relayTargetKey,proto3" json:"relay_target_key,omitempty"` // Target node pubkey (set by sender when routing via relay)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_tailbus_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Envelope) GetFromHandle() string {
	if x != nil {
		return x.FromHandle
	}
	return ""
}

func (x *Envelope) GetToHandle() string {
	if x != nil {
		return x.ToHandle
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Envelope) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

func (x *Envelope) GetType() EnvelopeType {
	if x != nil {
		return x.Type
	}
	return EnvelopeType_ENVELOPE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetAckId() string {
	if x != nil {
		return x.AckId
	}
	return ""
}

func (x *Envelope) GetRelayTargetKey() []byte {
	if x != nil {
		return x.RelayTargetKey
	}
	return nil
}

type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	HomeNodeId    string                 `protobuf:"bytes,4,opt,name=home_node_id,json=homeNodeId,proto3" json:"home_node_id,omitempty"`
	Members       []string               `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	NextSeq       uint64                 `protobuf:"varint,7,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,9,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_tailbus_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoomInfo) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *RoomInfo) GetHomeNodeId() string {
	if x != nil {
		return x.HomeNodeId
	}
	return ""
}

func (x *RoomInfo) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoomInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoomInfo) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *RoomInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *RoomInfo) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type RoomEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomSeq       uint64                 `protobuf:"varint,3,opt,name=room_seq,json=roomSeq,proto3" json:"room_seq,omitempty"`
	SenderHandle  string                 `protobuf:"bytes,4,opt,name=sender_handle,json=senderHandle,proto3" json:"sender_handle,omitempty"`
	SubjectHandle string                 `protobuf:"bytes,5,opt,name=subject_handle,json=subjectHandle,proto3" json:"subject_handle,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType   string                 `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SentAtUnix    int64                  `protobuf:"varint,8,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	Type          RoomEventType          `protobuf:"varint,9,opt,name=type,proto3,enum=tailbus.v1.RoomEventType" json:"type,omitempty"`
	TraceId       string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Members       []string               `protobuf:"bytes,11,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEvent) Reset() {
	*x = RoomEvent{}
	mi := &file_tailbus_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent) ProtoMessage() {}

func (x *RoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent.ProtoReflect.Descriptor instead.
func (*RoomEvent) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RoomEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RoomEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEvent) GetRoomSeq() uint64 {
	if x != nil {
		return x.RoomSeq
	}
	return 0
}

func (x *RoomEvent) GetSenderHandle() string {
	if x != nil {
		return x.SenderHandle
	}
	return ""
}

func (x *RoomEvent) GetSubjectHandle() string {
	if x != nil {
		return x.SubjectHandle
	}
	return ""
}

func (x *RoomEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RoomEvent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RoomEvent) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

func (x *RoomEvent) GetType() RoomEventType {
	if x != nil {
		return x.Type
	}
	return RoomEventType_ROOM_EVENT_TYPE_UNSPECIFIED
}

func (x *RoomEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RoomEvent) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type RoomCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Type            RoomCommandType        `protobuf:"varint,2,opt,name=type,proto3,enum=tailbus.v1.RoomCommandType" json:"type,omitempty"`
	RoomId          string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RequesterHandle string                 `protobuf:"bytes,4,opt,name=requester_handle,json=requesterHandle,proto3" json:"requester_handle,omitempty"`
	Title           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Members         []string               `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	SubjectHandle   string                 `protobuf:"bytes,7,opt,name=subject_handle,json=subjectHandle,proto3" json:"subject_handle,omitempty"`
	Payload         []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType     string                 `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	TraceId         string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SinceSeq        uint64                 `protobuf:"varint,11,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	RequesterNodeId string                 `protobuf:"bytes,12,opt,name=requester_node_id,json=requesterNodeId,proto3" json:"requester_node_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomCommand) Reset() {
	*x = RoomCommand{}
	mi := &file_tailbus_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCommand) ProtoMessage() {}

func (x *RoomCommand) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCommand.ProtoReflect.Descriptor instead.
func (*RoomCommand) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RoomCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RoomCommand) GetType() RoomCommandType {
	if x != nil {
		return x.Type
	}
	return RoomCommandType_ROOM_COMMAND_TYPE_UNSPECIFIED
}

func (x *RoomCommand) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomCommand) GetRequesterHandle() string {
	if x != nil {
		return x.RequesterHandle
	}
	return ""
}

func (x *RoomCommand) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoomCommand) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoomCommand) GetSubjectHandle() string {
	if x != nil {
		return x.SubjectHandle
	}
	return ""
}

func (x *RoomCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RoomCommand) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RoomCommand) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RoomCommand) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *RoomCommand) GetRequesterNodeId() string {
	if x != nil {
		return x.RequesterNodeId
	}
	return ""
}

type RoomCommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Room          *RoomInfo              `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	Event         *RoomEvent             `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Events        []*RoomEvent           `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	Members       []string               `protobuf:"bytes,7,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCommandResult) Reset() {
	*x = RoomCommandResult{}
	mi := &file_tailbus_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCommandResult) ProtoMessage() {}

func (x *RoomCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCommandResult.ProtoReflect.Descriptor instead.
func (*RoomCommandResult) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RoomCommandResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RoomCommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RoomCommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RoomCommandResult) GetRoom() *RoomInfo {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *RoomCommandResult) GetEvent() *RoomEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RoomCommandResult) GetEvents() []*RoomEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *RoomCommandResult) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type CommandSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersSchema string                 `protobuf:"bytes,3,opt,name=parameters_schema,json=parametersSchema,proto3" json:"parameters_schema,omitempty"` // optional JSON Schema
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommandSpec) Reset() {
	*x = CommandSpec{}
	mi := &file_tailbus_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSpec) ProtoMessage() {}

func (x *CommandSpec) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSpec.ProtoReflect.Descriptor instead.
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CommandSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandSpec) GetParametersSchema() string {
	if x != nil {
		return x.ParametersSchema
	}
	return ""
}

type ServiceManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Commands      []*CommandSpec         `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Domains       []string               `protobuf:"bytes,6,rep,name=domains,proto3" json:"domains,omitempty"`
	InputTypes    []string               `protobuf:"bytes,7,rep,name=input_types,json=inputTypes,proto3" json:"input_types,omitempty"`
	OutputTypes   []string               `protobuf:"bytes,8,rep,name=output_types,json=outputTypes,proto3" json:"output_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceManifest) Reset() {
	*x = ServiceManifest{}
	mi := &file_tailbus_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceManifest) ProtoMessage() {}

func (x *ServiceManifest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceManifest.ProtoReflect.Descriptor instead.
func (*ServiceManifest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceManifest) GetCommands() []*CommandSpec {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ServiceManifest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ServiceManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceManifest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ServiceManifest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *ServiceManifest) GetInputTypes() []string {
	if x != nil {
		return x.InputTypes
	}
	return nil
}

func (x *ServiceManifest) GetOutputTypes() []string {
	if x != nil {
		return x.OutputTypes
	}
	return nil
}

var File_tailbus_v1_messages_proto protoreflect.FileDescriptor

const file_tailbus_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x19tailbus/v1/messages.proto\x12\n" +
	"tailbus.v1\"\x8b\x03\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vfrom_handle\x18\x03 \x01(\tR\n" +
	"fromHandle\x12\x1b\n" +
	"\tto_handle\x18\x04 \x01(\tR\btoHandle\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12 \n" +
	"\fsent_at_unix\x18\a \x01(\x03R\n" +
	"sentAtUnix\x12,\n" +
	"\x04type\x18\b \x01(\x0e2\x18.tailbus.v1.EnvelopeTypeR\x04type\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\x12\x15\n" +
	"\x06ack_id\x18\v \x01(\tR\x05ackId\x12(\n" +
	"\x10relay_target_key\x18\f \x01(\fR\x0erelayTargetKey\"\x97\x02\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x12 \n" +
	"\fhome_node_id\x18\x04 \x01(\tR\n" +
	"homeNodeId\x12\x18\n" +
	"\amembers\x18\x05 \x03(\tR\amembers\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x19\n" +
	"\bnext_seq\x18\a \x01(\x04R\anextSeq\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\t \x01(\x03R\rupdatedAtUnix\"\xe9\x02\n" +
	"\tRoomEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\broom_seq\x18\x03 \x01(\x04R\aroomSeq\x12#\n" +
	"\rsender_handle\x18\x04 \x01(\tR\fsenderHandle\x12%\n" +
	"\x0esubject_handle\x18\x05 \x01(\tR\rsubjectHandle\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x12 \n" +
	"\fsent_at_unix\x18\b \x01(\x03R\n" +
	"sentAtUnix\x12-\n" +
	"\x04type\x18\t \x01(\x0e2\x19.tailbus.v1.RoomEventTypeR\x04type\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12\x18\n" +
	"\amembers\x18\v \x03(\tR\amembers\"\x99\x03\n" +
	"\vRoomCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.tailbus.v1.RoomCommandTypeR\x04type\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12)\n" +
	"\x10requester_handle\x18\x04 \x01(\tR\x0frequesterHandle\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\amembers\x18\x06 \x03(\tR\amembers\x12%\n" +
	"\x0esubject_handle\x18\a \x01(\tR\rsubjectHandle\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\t \x01(\tR\vcontentType\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12\x1b\n" +
	"\tsince_seq\x18\v \x01(\x04R\bsinceSeq\x12*\n" +
	"\x11requester_node_id\x18\f \x01(\tR\x0frequesterNodeId\"\xf8\x01\n" +
	"\x11RoomCommandResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12(\n" +
	"\x04room\x18\x04 \x01(\v2\x14.tailbus.v1.RoomInfoR\x04room\x12+\n" +
	"\x05event\x18\x05 \x01(\v2\x15.tailbus.v1.RoomEventR\x05event\x12-\n" +
	"\x06events\x18\x06 \x03(\v2\x15.tailbus.v1.RoomEventR\x06events\x12\x18\n" +
	"\amembers\x18\a \x03(\tR\amembers\"p\n" +
	"\vCommandSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x11parameters_schema\x18\x03 \x01(\tR\x10parametersSchema\"\x98\x02\n" +
	"\x0fServiceManifest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x123\n" +
	"\bcommands\x18\x02 \x03(\v2\x17.tailbus.v1.CommandSpecR\bcommands\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12\x18\n" +
	"\adomains\x18\x06 \x03(\tR\adomains\x12\x1f\n" +
	"\vinput_types\x18\a \x03(\tR\n" +
	"inputTypes\x12!\n" +
	"\foutput_types\x18\b \x03(\tR\voutputTypes*\xa2\x01\n" +
	"\fEnvelopeType\x12\x1d\n" +
	"\x19ENVELOPE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ENVELOPE_TYPE_MESSAGE\x10\x01\x12\x1e\n" +
	"\x1aENVELOPE_TYPE_SESSION_OPEN\x10\x02\x12!\n" +
	"\x1dENVELOPE_TYPE_SESSION_RESOLVE\x10\x03\x12\x15\n" +
	"\x11ENVELOPE_TYPE_ACK\x10\x04*\xb9\x01\n" +
	"\rRoomEventType\x12\x1f\n" +
	"\x1bROOM_EVENT_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dROOM_EVENT_TYPE_MEMBER_JOINED\x10\x01\x12\x1f\n" +
	"\x1bROOM_EVENT_TYPE_MEMBER_LEFT\x10\x02\x12\"\n" +
	"\x1eROOM_EVENT_TYPE_MESSAGE_POSTED\x10\x03\x12\x1f\n" +
	"\x1bROOM_EVENT_TYPE_ROOM_CLOSED\x10\x04*\x86\x02\n" +
	"\x0fRoomCommandType\x12!\n" +
	"\x1dROOM_COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ROOM_COMMAND_TYPE_CREATE\x10\x01\x12\x1a\n" +
	"\x16ROOM_COMMAND_TYPE_JOIN\x10\x02\x12\x1b\n" +
	"\x17ROOM_COMMAND_TYPE_LEAVE\x10\x03\x12\x1a\n" +
	"\x16ROOM_COMMAND_TYPE_POST\x10\x04\x12\x1c\n" +
	"\x18ROOM_COMMAND_TYPE_REPLAY\x10\x05\x12\"\n" +
	"\x1eROOM_COMMAND_TYPE_LIST_MEMBERS\x10\x06\x12\x1b\n" +
	"\x17ROOM_COMMAND_TYPE_CLOSE\x10\aB0Z.github.com/alexanderfrey/tailbus/api/messagepbb\x06proto3"

var (
	file_tailbus_v1_messages_proto_rawDescOnce sync.Once
	file_tailbus_v1_messages_proto_rawDescData []byte
)

func file_tailbus_v1_messages_proto_rawDescGZIP() []byte {
	file_tailbus_v1_messages_proto_rawDescOnce.Do(func() {
		file_tailbus_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tailbus_v1_messages_proto_rawDesc), len(file_tailbus_v1_messages_proto_rawDesc)))
	})
	return file_tailbus_v1_messages_proto_rawDescData
}

var file_tailbus_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tailbus_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tailbus_v1_messages_proto_goTypes = []any{
	(EnvelopeType)(0),         // 0: tailbus.v1.EnvelopeType
	(RoomEventType)(0),        // 1: tailbus.v1.RoomEventType
	(RoomCommandType)(0),      // 2: tailbus.v1.RoomCommandType
	(*Envelope)(nil),          // 3: tailbus.v1.Envelope
	(*RoomInfo)(nil),          // 4: tailbus.v1.RoomInfo
	(*RoomEvent)(nil),         // 5: tailbus.v1.RoomEvent
	(*RoomCommand)(nil),       // 6: tailbus.v1.RoomCommand
	(*RoomCommandResult)(nil), // 7: tailbus.v1.RoomCommandResult
	(*CommandSpec)(nil),       // 8: tailbus.v1.CommandSpec
	(*ServiceManifest)(nil),   // 9: tailbus.v1.ServiceManifest
}
var file_tailbus_v1_messages_proto_depIdxs = []int32{
	0, // 0: tailbus.v1.Envelope.type:type_name -> tailbus.v1.EnvelopeType
	1, // 1: tailbus.v1.RoomEvent.type:type_name -> tailbus.v1.RoomEventType
	2, // 2: tailbus.v1.RoomCommand.type:type_name -> tailbus.v1.RoomCommandType
	4, // 3: tailbus.v1.RoomCommandResult.room:type_name -> tailbus.v1.RoomInfo
	5, // 4: tailbus.v1.RoomCommandResult.event:type_name -> tailbus.v1.RoomEvent
	5, // 5: tailbus.v1.RoomCommandResult.events:type_name -> tailbus.v1.RoomEvent
	8, // 6: tailbus.v1.ServiceManifest.commands:type_name -> tailbus.v1.CommandSpec
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_tailbus_v1_messages_proto_init() }
func file_tailbus_v1_messages_proto_init() {
	if File_tailbus_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tailbus_v1_messages_proto_rawDesc), len(file_tailbus_v1_messages_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tailbus_v1_messages_proto_goTypes,
		DependencyIndexes: file_tailbus_v1_messages_proto_depIdxs,
		EnumInfos:         file_tailbus_v1_messages_proto_enumTypes,
		MessageInfos:      file_tailbus_v1_messages_proto_msgTypes,
	}.Build()
	File_tailbus_v1_messages_proto = out.File
	file_tailbus_v1_messages_proto_goTypes = nil
	file_tailbus_v1_messages_proto_depIdxs = nil
}
