// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: tailbus/v1/coord.proto

package coordpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinationAPI_RegisterNode_FullMethodName         = "/tailbus.v1.CoordinationAPI/RegisterNode"
	CoordinationAPI_WatchPeerMap_FullMethodName         = "/tailbus.v1.CoordinationAPI/WatchPeerMap"
	CoordinationAPI_LookupHandle_FullMethodName         = "/tailbus.v1.CoordinationAPI/LookupHandle"
	CoordinationAPI_UpsertRoom_FullMethodName           = "/tailbus.v1.CoordinationAPI/UpsertRoom"
	CoordinationAPI_LookupRoom_FullMethodName           = "/tailbus.v1.CoordinationAPI/LookupRoom"
	CoordinationAPI_ListRoomsForHandle_FullMethodName   = "/tailbus.v1.CoordinationAPI/ListRoomsForHandle"
	CoordinationAPI_Heartbeat_FullMethodName            = "/tailbus.v1.CoordinationAPI/Heartbeat"
	CoordinationAPI_CreateTeam_FullMethodName           = "/tailbus.v1.CoordinationAPI/CreateTeam"
	CoordinationAPI_ListTeams_FullMethodName            = "/tailbus.v1.CoordinationAPI/ListTeams"
	CoordinationAPI_GetTeamMembers_FullMethodName       = "/tailbus.v1.CoordinationAPI/GetTeamMembers"
	CoordinationAPI_CreateTeamInvite_FullMethodName     = "/tailbus.v1.CoordinationAPI/CreateTeamInvite"
	CoordinationAPI_AcceptTeamInvite_FullMethodName     = "/tailbus.v1.CoordinationAPI/AcceptTeamInvite"
	CoordinationAPI_RemoveTeamMember_FullMethodName     = "/tailbus.v1.CoordinationAPI/RemoveTeamMember"
	CoordinationAPI_UpdateTeamMemberRole_FullMethodName = "/tailbus.v1.CoordinationAPI/UpdateTeamMemberRole"
	CoordinationAPI_DeleteTeam_FullMethodName           = "/tailbus.v1.CoordinationAPI/DeleteTeam"
)

// CoordinationAPIClient is the client API for CoordinationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinationAPIClient interface {
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	WatchPeerMap(ctx context.Context, in *WatchPeerMapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerMapUpdate], error)
	LookupHandle(ctx context.Context, in *LookupHandleRequest, opts ...grpc.CallOption) (*LookupHandleResponse, error)
	UpsertRoom(ctx context.Context, in *UpsertRoomRequest, opts ...grpc.CallOption) (*UpsertRoomResponse, error)
	LookupRoom(ctx context.Context, in *LookupRoomRequest, opts ...grpc.CallOption) (*LookupRoomResponse, error)
	ListRoomsForHandle(ctx context.Context, in *ListRoomsForHandleRequest, opts ...grpc.CallOption) (*ListRoomsForHandleResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error)
	ListTeams(ctx context.Context, in *ListTeamsRequest, opts ...grpc.CallOption) (*ListTeamsResponse, error)
	GetTeamMembers(ctx context.Context, in *GetTeamMembersRequest, opts ...grpc.CallOption) (*GetTeamMembersResponse, error)
	CreateTeamInvite(ctx context.Context, in *CreateTeamInviteRequest, opts ...grpc.CallOption) (*CreateTeamInviteResponse, error)
	AcceptTeamInvite(ctx context.Context, in *AcceptTeamInviteRequest, opts ...grpc.CallOption) (*AcceptTeamInviteResponse, error)
	RemoveTeamMember(ctx context.Context, in *RemoveTeamMemberRequest, opts ...grpc.CallOption) (*RemoveTeamMemberResponse, error)
	UpdateTeamMemberRole(ctx context.Context, in *UpdateTeamMemberRoleRequest, opts ...grpc.CallOption) (*UpdateTeamMemberRoleResponse, error)
	DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error)
}

type coordinationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinationAPIClient(cc grpc.ClientConnInterface) CoordinationAPIClient {
	return &coordinationAPIClient{cc}
}

func (c *coordinationAPIClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) WatchPeerMap(ctx context.Context, in *WatchPeerMapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerMapUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinationAPI_ServiceDesc.Streams[0], CoordinationAPI_WatchPeerMap_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPeerMapRequest, PeerMapUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinationAPI_WatchPeerMapClient = grpc.ServerStreamingClient[PeerMapUpdate]

func (c *coordinationAPIClient) LookupHandle(ctx context.Context, in *LookupHandleRequest, opts ...grpc.CallOption) (*LookupHandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupHandleResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_LookupHandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) UpsertRoom(ctx context.Context, in *UpsertRoomRequest, opts ...grpc.CallOption) (*UpsertRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRoomResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_UpsertRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) LookupRoom(ctx context.Context, in *LookupRoomRequest, opts ...grpc.CallOption) (*LookupRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupRoomResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_LookupRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) ListRoomsForHandle(ctx context.Context, in *ListRoomsForHandleRequest, opts ...grpc.CallOption) (*ListRoomsForHandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoomsForHandleResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_ListRoomsForHandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTeamResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_CreateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) ListTeams(ctx context.Context, in *ListTeamsRequest, opts ...grpc.CallOption) (*ListTeamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTeamsResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_ListTeams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) GetTeamMembers(ctx context.Context, in *GetTeamMembersRequest, opts ...grpc.CallOption) (*GetTeamMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamMembersResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_GetTeamMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) CreateTeamInvite(ctx context.Context, in *CreateTeamInviteRequest, opts ...grpc.CallOption) (*CreateTeamInviteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTeamInviteResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_CreateTeamInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) AcceptTeamInvite(ctx context.Context, in *AcceptTeamInviteRequest, opts ...grpc.CallOption) (*AcceptTeamInviteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptTeamInviteResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_AcceptTeamInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) RemoveTeamMember(ctx context.Context, in *RemoveTeamMemberRequest, opts ...grpc.CallOption) (*RemoveTeamMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTeamMemberResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_RemoveTeamMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) UpdateTeamMemberRole(ctx context.Context, in *UpdateTeamMemberRoleRequest, opts ...grpc.CallOption) (*UpdateTeamMemberRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTeamMemberRoleResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_UpdateTeamMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTeamResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_DeleteTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinationAPIServer is the server API for CoordinationAPI service.
// All implementations must embed UnimplementedCoordinationAPIServer
// for forward compatibility.
type CoordinationAPIServer interface {
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	WatchPeerMap(*WatchPeerMapRequest, grpc.ServerStreamingServer[PeerMapUpdate]) error
	LookupHandle(context.Context, *LookupHandleRequest) (*LookupHandleResponse, error)
	UpsertRoom(context.Context, *UpsertRoomRequest) (*UpsertRoomResponse, error)
	LookupRoom(context.Context, *LookupRoomRequest) (*LookupRoomResponse, error)
	ListRoomsForHandle(context.Context, *ListRoomsForHandleRequest) (*ListRoomsForHandleResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error)
	ListTeams(context.Context, *ListTeamsRequest) (*ListTeamsResponse, error)
	GetTeamMembers(context.Context, *GetTeamMembersRequest) (*GetTeamMembersResponse, error)
	CreateTeamInvite(context.Context, *CreateTeamInviteRequest) (*CreateTeamInviteResponse, error)
	AcceptTeamInvite(context.Context, *AcceptTeamInviteRequest) (*AcceptTeamInviteResponse, error)
	RemoveTeamMember(context.Context, *RemoveTeamMemberRequest) (*RemoveTeamMemberResponse, error)
	UpdateTeamMemberRole(context.Context, *UpdateTeamMemberRoleRequest) (*UpdateTeamMemberRoleResponse, error)
	DeleteTeam(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error)
	mustEmbedUnimplementedCoordinationAPIServer()
}

// UnimplementedCoordinationAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinationAPIServer struct{}

func (UnimplementedCoordinationAPIServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedCoordinationAPIServer) WatchPeerMap(*WatchPeerMapRequest, grpc.ServerStreamingServer[PeerMapUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchPeerMap not implemented")
}
func (UnimplementedCoordinationAPIServer) LookupHandle(context.Context, *LookupHandleRequest) (*LookupHandleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupHandle not implemented")
}
func (UnimplementedCoordinationAPIServer) UpsertRoom(context.Context, *UpsertRoomRequest) (*UpsertRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertRoom not implemented")
}
func (UnimplementedCoordinationAPIServer) LookupRoom(context.Context, *LookupRoomRequest) (*LookupRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupRoom not implemented")
}
func (UnimplementedCoordinationAPIServer) ListRoomsForHandle(context.Context, *ListRoomsForHandleRequest) (*ListRoomsForHandleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoomsForHandle not implemented")
}
func (UnimplementedCoordinationAPIServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCoordinationAPIServer) CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTeam not implemented")
}
func (UnimplementedCoordinationAPIServer) ListTeams(context.Context, *ListTeamsRequest) (*ListTeamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeams not implemented")
}
func (UnimplementedCoordinationAPIServer) GetTeamMembers(context.Context, *GetTeamMembersRequest) (*GetTeamMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeamMembers not implemented")
}
func (UnimplementedCoordinationAPIServer) CreateTeamInvite(context.Context, *CreateTeamInviteRequest) (*CreateTeamInviteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTeamInvite not implemented")
}
func (UnimplementedCoordinationAPIServer) AcceptTeamInvite(context.Context, *AcceptTeamInviteRequest) (*AcceptTeamInviteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptTeamInvite not implemented")
}
func (UnimplementedCoordinationAPIServer) RemoveTeamMember(context.Context, *RemoveTeamMemberRequest) (*RemoveTeamMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTeamMember not implemented")
}
func (UnimplementedCoordinationAPIServer) UpdateTeamMemberRole(context.Context, *UpdateTeamMemberRoleRequest) (*UpdateTeamMemberRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTeamMemberRole not implemented")
}
func (UnimplementedCoordinationAPIServer) DeleteTeam(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (UnimplementedCoordinationAPIServer) mustEmbedUnimplementedCoordinationAPIServer() {}
func (UnimplementedCoordinationAPIServer) testEmbeddedByValue()                         {}

// UnsafeCoordinationAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinationAPIServer will
// result in compilation errors.
type UnsafeCoordinationAPIServer interface {
	mustEmbedUnimplementedCoordinationAPIServer()
}

func RegisterCoordinationAPIServer(s grpc.ServiceRegistrar, srv CoordinationAPIServer) {
	// If the following call panics, it indicates UnimplementedCoordinationAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinationAPI_ServiceDesc, srv)
}

func _CoordinationAPI_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_WatchPeerMap_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPeerMapRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinationAPIServer).WatchPeerMap(m, &grpc.GenericServerStream[WatchPeerMapRequest, PeerMapUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinationAPI_WatchPeerMapServer = grpc.ServerStreamingServer[PeerMapUpdate]

func _CoordinationAPI_LookupHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).LookupHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_LookupHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).LookupHandle(ctx, req.(*LookupHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_UpsertRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).UpsertRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_UpsertRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).UpsertRoom(ctx, req.(*UpsertRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_LookupRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).LookupRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_LookupRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).LookupRoom(ctx, req.(*LookupRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_ListRoomsForHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomsForHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).ListRoomsForHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_ListRoomsForHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).ListRoomsForHandle(ctx, req.(*ListRoomsForHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_CreateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).CreateTeam(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_ListTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).ListTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_ListTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).ListTeams(ctx, req.(*ListTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_GetTeamMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).GetTeamMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_GetTeamMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).GetTeamMembers(ctx, req.(*GetTeamMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_CreateTeamInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).CreateTeamInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_CreateTeamInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).CreateTeamInvite(ctx, req.(*CreateTeamInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_AcceptTeamInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptTeamInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).AcceptTeamInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_AcceptTeamInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).AcceptTeamInvite(ctx, req.(*AcceptTeamInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_RemoveTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).RemoveTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_RemoveTeamMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).RemoveTeamMember(ctx, req.(*RemoveTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_UpdateTeamMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).UpdateTeamMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_UpdateTeamMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).UpdateTeamMemberRole(ctx, req.(*UpdateTeamMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_DeleteTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).DeleteTeam(ctx, req.(*DeleteTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinationAPI_ServiceDesc is the grpc.ServiceDesc for CoordinationAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinationAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tailbus.v1.CoordinationAPI",
	HandlerType: (*CoordinationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _CoordinationAPI_RegisterNode_Handler,
		},
		{
			MethodName: "LookupHandle",
			Handler:    _CoordinationAPI_LookupHandle_Handler,
		},
		{
			MethodName: "UpsertRoom",
			Handler:    _CoordinationAPI_UpsertRoom_Handler,
		},
		{
			MethodName: "LookupRoom",
			Handler:    _CoordinationAPI_LookupRoom_Handler,
		},
		{
			MethodName: "ListRoomsForHandle",
			Handler:    _CoordinationAPI_ListRoomsForHandle_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CoordinationAPI_Heartbeat_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _CoordinationAPI_CreateTeam_Handler,
		},
		{
			MethodName: "ListTeams",
			Handler:    _CoordinationAPI_ListTeams_Handler,
		},
		{
			MethodName: "GetTeamMembers",
			Handler:    _CoordinationAPI_GetTeamMembers_Handler,
		},
		{
			MethodName: "CreateTeamInvite",
			Handler:    _CoordinationAPI_CreateTeamInvite_Handler,
		},
		{
			MethodName: "AcceptTeamInvite",
			Handler:    _CoordinationAPI_AcceptTeamInvite_Handler,
		},
		{
			MethodName: "RemoveTeamMember",
			Handler:    _CoordinationAPI_RemoveTeamMember_Handler,
		},
		{
			MethodName: "UpdateTeamMemberRole",
			Handler:    _CoordinationAPI_UpdateTeamMemberRole_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _CoordinationAPI_DeleteTeam_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPeerMap",
			Handler:       _CoordinationAPI_WatchPeerMap_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tailbus/v1/coord.proto",
}
